[package]
name = "BucketFountainPeriphery"
version = "0.0.2"
# published-at = "0x8e8f891d9202c5366bff7c3005761f26a5abedeaf436d76b7d8e8b7794126d7b"
published-at = "0x8d5c100f70eec682118fab24756fb2540c3aa8de253546022d219d18d68b2b94"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
# Bucket
BucketProtocol = { local = "../v1-core/protocol" }
# Aftermath
AftermathAmm = { local = "./aftermath-interfaces/packages/amm/amm" }
ProtocolFeeVault = { local = "./aftermath-interfaces/packages/amm/amm-protocol-fee-vault" }
InsuranceFund = { local = "./aftermath-interfaces/packages/amm/amm-insurance-fund" }
Treasury = { local = "./aftermath-interfaces/packages/amm/amm-treasury" }
ReferralVault = { local = "./aftermath-interfaces/packages/amm/amm-referral-vault" }
# Cetus
CetusClmm = { local = "../cetus-lp-vault/cetus-clmm/clmmpool" }
CetusIntegrate = { local = "../cetus-lp-vault/cetus-clmm/integrate" }
# Fountain
BucketFountain = { git = "https://github.com/Bucket-Protocol/fountain.git", rev = "main" }
# Strater Cetus Vault
StraterLpVault = { local = "../cetus-lp-vault" }

[addresses]
bucket_fountain_periphery = "0x8e8f891d9202c5366bff7c3005761f26a5abedeaf436d76b7d8e8b7794126d7b"
# bucket_fountain_periphery = "0x0"
